version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - minio
    environment:
      MONGO_URI: mongodb://mongo:27017/fileshare
    networks:
      - fileshare_network

  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    networks:
      - fileshare_network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: goat
      POSTGRES_DB: fileshare
    volumes:
      - post-data:/data/db
    networks:
      - fileshare_network

volumes:
  mongo-data:
  post-data:
  minio-data:

networks:
  fileshare_network:
