version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - postgres
    environment:
      MONGO_URI: mongodb://mongo:27017/fileshare
    networks:
      - fileshare_network

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    networks:
      - fileshare_network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: goat
      POSTGRES_DB: fileshare
    volumes:
      - post-data:/data/db
    networks:
      - fileshare_network

volumes:
  mongo-data:
  post-data:

networks:
  fileshare_network:
    driver: bridge
